#!/bin/sh

_pkgconf() {
    pkgconf --libs --cflags "$1" 2>/dev/null || printf '%s' "$2"
}

_cc() {
    printf '%s %s\n' "${CC:=cc}" "$1"

    _file=$1
    shift

    set -f -- src/[!k]*.o src/action/*.o "$@"

    "$CC" -Iinclude -O0 -g $(_pkgconf libcurl -lcurl) $LDFLAGS "$@" \
        -o "${_file%%.c}" "$_file"

    set +f
}

_valgrind() {
    valgrind \
        --leak-check=full \
        --show-leak-kinds=all \
        --track-origins=yes \
        --error-exitcode=1 \
        "$@"
}

set -e
set -- test/*.c

for file do
    _cc "$file"
done

for file do
    _valgrind "${file%%.c}"

    rm -f "${file%%.c}"
done

_valgrind ./kiss v
_valgrind ./kiss
