#!/bin/sh

_cc() {
    printf '%s %s\n' "${CC:=cc}" "$1"

    _file=$1
    shift

    set -- src/[!k]*.o src/action/*.o "$@"
    set -f

    "$CC" -Iinclude -O0 -g "$@" -o "${_file%%.c}" "$_file" -lcurl $LDFLAGS

    set +f
}

_valgrind() {
    "${VALGRIND:=valgrind}" \
        --leak-check=full \
        --show-leak-kinds=all \
        --track-origins=yes \
        --error-exitcode=1 \
        "$@"
}

set -e
set -- test/*.c

for file do
    _cc "$file"
done

for file do
    _valgrind "${file%%.c}"

    rm -f "${file%%.c}"
done

_valgrind ./kiss v
_valgrind ./kiss
