#!/bin/sh

dep() {
    pkg-config --libs --cflags "${static:+--static}" "$1" ||
    printf '%s\n' "$2"
}

run() {
    printf '%s\n' "$*"
    "$@"
}

build() {
    for obj do
        run "${CC:=cc}" $CFLAGS $CPPFLAGS -c -o "${obj%%.c}.o" "$obj"
    done

    run "${CC:=cc}" $CPPFLAGS -o kiss "$@" $LDFLAGS
}

main() {
    CFLAGS="-std=c99 -D_POSIX_C_SOURCE=200809L -Wall -Wextra -pedantic $CFLAGS"
    CPPFLAGS="-Iinclude $CPPFLAGS"

    case " $LDFLAGS " in *" -static "*)
        static=1
    esac

    case ${CURL:=1} in 1)
        LDFLAGS="$(dep libcurl -lcurl) $LDFLAGS"
        CFLAGS="-DUSE_CURL $CFLAGS"
    esac

    case ${OPENSSL:=1} in 1)
        LDFLAGS="$(dep openssl '-lssl -lcrypto') $LDFLAGS"
        CFLAGS="-DUSE_OPENSSL $CFLAGS"
    esac

    build src/*.c src/*/*.c
}

main
