name: CI
on: [push, pull_request]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Run CI.
              run: |
                  sudo apt-get install tcc
                  export CFLAGS="$CFLAGS -Werror"
                  CC=gcc   make -B
                  CC=clang make -B
                  CC=tcc   make -B
