name: CI
on: [push, pull_request]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Run CI.
              run: |
                  sudo apt install valgrind
                  CFLAGS=-Werror CC=gcc   make -B
                  CFLAGS=-Werror CC=clang make -B
                  git clone --depth=1 https://github.com/kisslinux/repo
                  KISS_PATH=$PWD/repo/core:$PWD/repo/extra make check
