name: CI
on: [push, pull_request]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Run CI.
              run: |
                  sudo apt install tcc valgrind libcurl4-openssl-dev
                  make clean
                  CFLAGS=-Werror CC=tcc   make
                  CFLAGS=-Werror CC=tcc   make check
                  make clean
                  CFLAGS=-Werror CC=clang make
                  CFLAGS=-Werror CC=clang make check
                  make clean
                  CFLAGS=-Werror CC=gcc   make
                  CFLAGS=-Werror CC=gcc   make check
