name: CI
on: [push, pull_request]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Run CI.
              run: |
                  sudo apt install tcc valgrind libcurl4-openssl-dev libarchive-dev
                  export OPENSSL=0
                  export LIBARCHIVE=1
                  export CFLAGS='-Werror -O3'
                  CC=clang time ./make
                  CC=tcc   time ./make
                  CC=gcc   time ./make
                  export CFLAGS='-Werror -O0 -g -fprofile-arcs -ftest-coverage'
                  export LDFLAGS='-lgcov --coverage'
                  CC=gcc ./make
                  ./make check

            - uses: codecov/codecov-action@v1
              with:
                  fail_ci_if_error: true
