name: CI
on: [push, pull_request]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Run CI.
              run: |
                  sudo apt install tcc valgrind libcurl4-openssl-dev

                  export CFLAGS=-Werror

                  make clean
                  CC=tcc   make
                  CC=tcc   make check

                  make clean
                  CC=clang make
                  CC=clang make check

                  make clean
                  CC=gcc   make
                  CC=gcc   make check

                  export CFLAGS='-fprofile-arcs -ftest-coverage'
                  export LDFLAGS='-lgcov --coverage'

                  make clean
                  CC=gcc   make
                  CC=gcc   make check

            - uses: codecov/codecov-action@v1
              with:
                  fail_ci_if_error: true
